// Authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GRADES_FETCH_SUCCESS = 'GRADES_FETCH_SUCCESS';
export const GRADES_FETCH_START = 'GRADES_FETCH_START';
export const GRADES_UPLOAD_START = 'GRADES_UPLOAD_START';
export const GRADES_UPLOAD_SUCCESS = 'GRADES_UPLOAD_SUCCESS';
export const GRADES_UPLOAD_FAIL = 'GRADES_UPLOAD_FAIL';
export const FILESELECTED = 'FILESELECTED';
export const FILEDESELECTED = 'FILEDESELECTED';
export const FILESELECTERROR = 'FILESELECTERROR';
