# Generated by Django 3.0.2 on 2020-02-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('name', 'subject', 'test')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'password')},
        ),
    ]
