# Generated by Django 3.0.2 on 2020-02-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200201_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
