# Generated by Django 3.0.2 on 2020-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200201_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(),
        ),
    ]
